# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Eddie Zhou
tagline:          Programmer, I think.
url:              http://eddiezhou.me
paginate:         1
baseurl:          /
author:			  TwelveNights
  name:           Eddie Zhou
  url:            https://github.com/TwelveNights
  email:          me@eddiezhou.me

# Custom vars
version:          1.0.0
github:			  TwelveNights
  repo:           https://github.com/TwelveNights/TwelveNights.github.io/

highlighter: pygments